// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liykllgnzlqqzjyvvygb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpeWtsbGduemxxcXpqeXZ2eWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODg3MTAsImV4cCI6MjA3MDA2NDcxMH0.jh0J8M0a8Qtm_whEzBSYTlZDwVNuTQB6jbpuuMhO5Zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});